# Generated by Django 4.2 on 2024-08-09 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(blank=True, default=-16.5, null=True)),
                ('longitud', models.FloatField(blank=True, default=-68.15, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('maquinaria', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_trabajo', models.TextField(default='Descripcion...')),
                ('foto_inicio', models.ImageField(blank=True, upload_to='trabajo')),
                ('foto_desarollo', models.ImageField(blank=True, upload_to='trabajo')),
                ('foto_culminado', models.ImageField(blank=True, upload_to='trabajo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaUrb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(default='El alto', max_length=50)),
                ('cordenadas', models.CharField(max_length=50)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.CharField(max_length=8)),
                ('ci', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('foto_solicitud', models.ImageField(blank=True, upload_to='trabajo')),
                ('ubicacion_direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, default=-16.5, null=True)),
                ('longitud', models.FloatField(blank=True, default=-68.15, null=True)),
                ('celular', models.IntegerField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.vecino')),
                ('zona_urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('ficha_operativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.fichaoperativa')),
                ('solicitud_vecino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.solicitudvecino')),
            ],
        ),
        migrations.AddField(
            model_name='fichaoperativa',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.vecino'),
        ),
        migrations.AddField(
            model_name='fichaoperativa',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito'),
        ),
        migrations.AddField(
            model_name='fichaoperativa',
            name='tecnico_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaoperativa',
            name='zonaurb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb'),
        ),
        migrations.CreateModel(
            name='CalleAv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('numero_vivienda', models.IntegerField()),
                ('zona_urb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
            ],
        ),
    ]
