# Generated by Django 4.2 on 2024-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vecino',
            name='codigo_usuario',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
