# Generated by Django 4.2 on 2024-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtecnica',
            name='descripcion_trabajo',
            field=models.TextField(default='Descripcion...'),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='foto_culminado',
            field=models.ImageField(blank=True, upload_to='trabajo'),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='foto_desarollo',
            field=models.ImageField(blank=True, upload_to='trabajo'),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='foto_inicio',
            field=models.ImageField(blank=True, upload_to='trabajo'),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='maquinaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtecnica',
            name='volumen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
